ALTER TABLE sales_customers
  ADD COLUMN fax VARCHAR(64) NULL DEFAULT NULL AFTER phone,
  ADD COLUMN bank_name VARCHAR(256) NULL DEFAULT NULL AFTER address,
  ADD COLUMN bank_account VARCHAR(128) NULL DEFAULT NULL AFTER bank_name,
  ADD COLUMN tax_id VARCHAR(64) NULL DEFAULT NULL AFTER bank_account;
